### ISSUE TITLE
Different pins?

### ISSUE THREAD

**Issue by carlni2008** [Panda381/PicoVGA#11]
Hi I am working on a pico motherboard. My question is that if it's possible to move the output to other pins, because I still want the uart pins for data transmission.

**Comment by Panda381** [comment]
The pins can be relocated by defining the VGA_GPIO_FIRST parameter in the vga_config.h file, which specifies the first GPIO pin of the VGA output. However, it is a condition (by PIO principle) that the pin numbers must form a continuous series.
